sonar.projectKey=supportflow
sonar.projectName=SupportFlow
sonar.sourceEncoding=UTF-8

sonar.sources=apps/web/src,apps/api/src
sonar.tests=apps/web/tests,apps/api/tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/tests/**

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/test-results/**,**/playwright-report/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/tests/**
